In [76]:
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import altair as alt

%matplotlib inline

In [52]:
def get_data(days, tickers):
    df = pd.DataFrame()
    for company in tickers.keys():
        tkr = yf.Ticker(tickers[company])
        hist = tkr.history(period=f'{days}d')
        hist.index = hist.index.strftime('%d %B %Y')
        hist = hist[['Close']]
        hist.columns = [company]
        hist = hist.T
        hist.index.name = 'Name'
        df = pd.concat([df, hist])
    return df

In [53]:
days = 50

tickers = {
    'apple': 'AAPL',
    'facebook': 'FB',
    'google': 'GOOGL',
    'microsoft': 'MSFT',
    'netflix': 'NFLX',
    'amazon': 'AMZN'
}

df = get_data(days, tickers)

Date,17 September 2021,20 September 2021,21 September 2021,22 September 2021,23 September 2021,24 September 2021,27 September 2021,28 September 2021,29 September 2021,30 September 2021,...,12 November 2021,15 November 2021,16 November 2021,17 November 2021,18 November 2021,19 November 2021,22 November 2021,23 November 2021,24 November 2021,26 November 2021
Name,,,,,,,,,,,,,,,,,,,,,
apple,145.847137,142.731689,143.220963,145.637451,146.616028,146.705887,145.158142,141.703186,142.621857,141.293793,...,149.990005,150.000000,151.000000,153.490005,157.869995,160.550003,161.020004,161.410004,161.940002,156.809998
facebook,364.720001,355.700012,357.480011,343.209991,345.959991,352.959991,353.579987,340.649994,339.609985,339.390015,...,340.890015,347.559998,342.959991,340.769989,338.690002,345.299988,341.010010,337.250000,341.059998,333.119995
google,2816.000000,2774.389893,2780.659912,2805.669922,2824.320068,2844.300049,2821.439941,2716.600098,2687.070068,2673.520020,...,2973.560059,2969.040039,2957.520020,2960.939941,2996.770020,2978.530029,2926.040039,2915.639893,2922.399902,2843.659912
microsoft,299.322388,293.762543,294.261627,298.034729,299.012939,298.803345,293.632812,283.002228,283.481354,281.405182,...,336.105103,335.456299,338.890015,339.119995,341.269989,343.109985,339.829987,337.679993,337.910004,329.679993
netflix,589.349976,575.429993,573.140015,590.650024,593.260010,592.390015,592.640015,583.849976,599.059998,610.340027,...,682.609985,679.330017,687.400024,691.690002,682.020020,678.799988,659.200012,654.059998,658.289978,665.640015
amazon,3462.520020,3355.729980,3343.629883,3380.050049,3416.000000,3425.520020,3405.800049,3315.959961,3301.120117,3285.040039,...,3525.149902,3545.679932,3540.699951,3549.000000,3696.060059,3676.570068,3572.570068,3580.040039,3580.409912,3504.560059

In [71]:
companies = ['apple', 'facebook']
data = df.loc[companies]
data

Date,17 September 2021,20 September 2021,21 September 2021,22 September 2021,23 September 2021,24 September 2021,27 September 2021,28 September 2021,29 September 2021,30 September 2021,...,12 November 2021,15 November 2021,16 November 2021,17 November 2021,18 November 2021,19 November 2021,22 November 2021,23 November 2021,24 November 2021,26 November 2021
Name,,,,,,,,,,,,,,,,,,,,,
apple,145.847137,142.731689,143.220963,145.637451,146.616028,146.705887,145.158142,141.703186,142.621857,141.293793,...,149.990005,150.000000,151.000000,153.490005,157.869995,160.550003,161.020004,161.410004,161.940002,156.809998
facebook,364.720001,355.700012,357.480011,343.209991,345.959991,352.959991,353.579987,340.649994,339.609985,339.390015,...,340.890015,347.559998,342.959991,340.769989,338.690002,345.299988,341.010010,337.250000,341.059998,333.119995

In [72]:
data.sort_index()

Date,17 September 2021,20 September 2021,21 September 2021,22 September 2021,23 September 2021,24 September 2021,27 September 2021,28 September 2021,29 September 2021,30 September 2021,...,12 November 2021,15 November 2021,16 November 2021,17 November 2021,18 November 2021,19 November 2021,22 November 2021,23 November 2021,24 November 2021,26 November 2021
Name,,,,,,,,,,,,,,,,,,,,,
apple,145.847137,142.731689,143.220963,145.637451,146.616028,146.705887,145.158142,141.703186,142.621857,141.293793,...,149.990005,150.000000,151.000000,153.490005,157.869995,160.550003,161.020004,161.410004,161.940002,156.809998
facebook,364.720001,355.700012,357.480011,343.209991,345.959991,352.959991,353.579987,340.649994,339.609985,339.390015,...,340.890015,347.559998,342.959991,340.769989,338.690002,345.299988,341.010010,337.250000,341.059998,333.119995

In [73]:
data = data.T.reset_index()

In [74]:
data = pd.melt(data, id_vars=['Date']).rename(columns={'value': 'Stock Prices (USD)'})
data

                 Date      Name  Stock Prices (USD)
0   17 September 2021     apple          145.847137
1   20 September 2021     apple          142.731689
2   21 September 2021     apple          143.220963
3   22 September 2021     apple          145.637451
4   23 September 2021     apple          146.616028
..                ...       ...                 ...
95   19 November 2021  facebook          345.299988
96   22 November 2021  facebook          341.010010
97   23 November 2021  facebook          337.250000
98   24 November 2021  facebook          341.059998
99   26 November 2021  facebook          333.119995

[100 rows x 3 columns]

In [77]:
chart = (
    alt.Chart(data)
    .mark_line(opacity=0.8)
    .encode(
        x="Date:T",
        y=alt.Y("Stock Prices (USD):Q", stack=None),
        color='Name:N'
    )
)

In [78]:
chart

alt.Chart(...)